# Generated by Django 4.2.7 on 2026-06-19 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('education', 'Education'), ('medical', 'Medical'), ('home', 'Home / Mortgage'), ('auto', 'Auto'), ('other', 'Other')], default='personal', max_length=20)),
                ('term_months', models.PositiveIntegerField(default=12, help_text='Repayment term in months')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, help_text='Additional information from the applicant')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Application',
                'verbose_name_plural': 'Grant Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('virtual_debit', 'Virtual Debit'), ('virtual_credit', 'Virtual Credit'), ('physical_debit', 'Physical Debit'), ('physical_credit', 'Physical Credit')], default='virtual_debit', max_length=20)),
                ('card_brand', models.CharField(default='Visa', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text='Name to print on the card', max_length=150)),
                ('delivery_address', models.TextField(blank=True, help_text='For physical cards')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Application',
                'verbose_name_plural': 'Card Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='virtual_debit', max_length=20)),
                ('card_brand', models.CharField(default='Visa', max_length=20)),
                ('card_holder', models.CharField(blank=True, max_length=150)),
                ('card_number', models.CharField(blank=True, help_text='Demo card number (display only)', max_length=19)),
                ('expiry', models.CharField(blank=True, help_text='MM/YY', max_length=7)),
                ('cvv', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='services.cardapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
